### ISSUE TITLE
How to set width on a per image basis?

### ISSUE THREAD

**Issue by kslstn** [robwierzbowski/jekyll-picture-tag#101]
Is it possible to set the base_width property on a per image basis? I'd like to use that in combination with a preset like this:

```
  default:
    markup: data_auto
    formats: [webp, original]
    pixel_ratios: [0.5, 1, 2, 2.5, 3]
```

**Comment by rbuchberger** [comment]
Are you asking to set widths per source image in the same tag? So use one set of widths for your desktop image, and another for your mobile image? I've written that functionality with pixels, but not with pixel ratios. You can use `media_widths` like so:

```yaml
media_widths: 
  mobile: [200, 400, 600] 
  tablet: [400, 600, 800]
```

You know that if you specify pixel ratios, that is the only criteria by which the browser will select images. It doesn't look at width on the screen or anything, it just picks the one which is closest to the device's pixel ratio. Most of the time widths are a better way to go, because then the browser accounts for both size on the screen and the device's pixel ratio.

If you're looking to use different widths for different places, just make more presets.
