### ISSUE TITLE
Fails if generated folder is not empty

### ISSUE THREAD

**Issue by egelmex** [robwierzbowski/jekyll-picture-tag#26]
steps to reproduce:

```
touch assests/images/generated/index.html
```

```
picture:
  source: "assets/images/_fullsize"
  output: "assets/images/generated"
  markup: "picturefill"
```

expected behaviour:
assets/images/generated should contain images and index.html

observed behaviour:
assets/images/generated only contains index.html
