### ISSUE TITLE
Prefer srcset “2x” syntax instead of separate <source> for HDPI

### ISSUE THREAD

**Issue by daneden** [robwierzbowski/jekyll-picture-tag#52]
I can’t seem to get the default HDPI media queries working, which is part of the reason I’m opening this issue. My own issue aside, I think it’s agreeable to prefer the [“Nx” syntax](http://scottjehl.github.io/picturefill/#media-and-srcset) defined in the `picture` element [specification](https://html.spec.whatwg.org/multipage/embedded-content.html#image-candidate-string)

More here: http://responsiveimages.org

**Comment by kyleaffolder** [comment]
+1

**Comment by nhoizey** [comment]
If you only target screen definition with fixed CSS dimensions, you don't even need `<picture>`, you should use `<img>` with `srcset-x` attributes.

**Comment by h0r0man** [comment]
I really 👍 for something like this:

```yml
picture:
  …
  presets:
    default:
      ppi: [1, 2]
      source_large
        media: "(min-width: 80em)"
        width: "960"
      source_medium
        media: "(min-width: 40em)"
        width: "480"
      source_default:
        width: "240"
```
```html
{% picture {{ image.jpg }} alt="Awesome" %}
<!-- compiled to: -->
<picture>
  <source media="(min-width: 80em)" srcset="image-960by960.jpg, image-1920by1920.jpg 2x">
  <source media="(min-width: 40em)" srcset="image-480by480.jpg, image-960by960.jpg 2x">
  <img src="image-240by240.jpg" srcset="image-480by480.jpg 2x" alt="Awesome">
 </picture>
```
