### ISSUE TITLE
Generated folder contains images multiple times after multiple site generations

### ISSUE THREAD

**Issue by funkenstrahlen** [robwierzbowski/jekyll-picture-tag#54]
My config looks like this:

``` Yaml
# Image-Tag presets
image:
  source: assets/images/
  output: generated
  presets:
    # Proportional preset
    default:
      width: 720
```

After running `jekyll generate` multiple times, each image appears multiple times in the generated folder.

Example:

```
incident-695x309-ae81c8.png
incident-695x309-af4c36.png
incident-695x309-b489a5.png
incident-695x309-ba62f1.png
incident-695x309-bebd5e.png
incident-695x309-bfefe2.png
incident-695x309-c4b627.png
```

I thought the regeneration might delete the old images or **better reuse the images it already resized**! What am I doing wrong? This takes a lot of generation time and a lot of space on my webserver.
