### ISSUE TITLE
Liquid Exception: No such file or directory - identify -ping

### ISSUE THREAD

**Issue by Gio-** [robwierzbowski/jekyll-picture-tag#74]
Hi, 
first thanks for all your hard work. I've got problems during the configuration of your plugin. When I use 

> bundle exec jekyll build

this is the result

```
C:\Users\Gio\Documents\GitHub\uselessdevlog` [master ≡ +3 ~4 -3 !]> bundle exec jekyll build
Configuration file: C:/Users/Gio/Documents/GitHub/uselessdevlog/_config.yml
            Source: C:/Users/Gio/Documents/GitHub/uselessdevlog
       Destination: C:/Users/Gio/Documents/GitHub/uselessdevlog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Generating coffee-550by364-40f0cb.jpg
      Liquid Exception: No such file or directory - identify -ping C:/Users/Gio/AppData/Local/Temp/mini_magick20160722-636-1o7pvo.jpg in index.html
                    done in 0.904 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

> **Liquid Exception: No such file or directory - identify -ping C:/Users/Gio/AppData/Local/Temp/mini_magick20160722-636-1o7pvo.jpg in index.html**

This is my `_config.yml`

```
# Picture Tag Config
picture:
  source: "/images/"
  output: "generated"
  markup: "picture"
  presets:
    main:
        ppi: [1, 1.5]
        attr:
            class: "img-responsive"
            itemprop: "image"
        source_medium:
            media: "(min-width: 992px)"
            width: "550"
        source_default: 
            width: "300"
    post:
        ppi: [1, 1.5]
        attr:
            class: "img-responsive"
            itemprop: "image"
        source_large:
            media: "(min-width: 1200px)"
            width: "750px"
        source_medium:
            media: "(min-width: 992px)"
            width: "550"
        source_default: 
            width: "300"
```

And my `Gemfile` 

```
source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins 
gem 'jekyll-picture-tag', '~> 0.3.0', group: :jekyll_plugins
```

I've tried uninstalling/reinstalling image_magick but it doesn't work.
