### ISSUE TITLE
Can't use any other presets -only the default one

### ISSUE THREAD

**Issue by neorganic** [robwierzbowski/jekyll-picture-tag#77]
```
picture:
  source: ""
  output: "generated"
  markup: "picture"
  presets:
    default:
      ppi: [1, 1.5, 2]   
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
        height: "300"
      source_default:
        width: "300"
    header:
      attr:
        class: "header-image"
        itemprop: "image"
      ppi: [1, 1.5, 2]
      source_medium:
        media: "(min-width: 5em)"
        width: "393"
        height: "260"
      source_default:
        width: "150"
```

Using this config with html : 

` {% picture [header]  /news-images/{{post.image}}  alt="{{post.title}} image" width="100%" %}`

Gives me images with the default settings - is it a bug or I am missing on something?
