### ISSUE TITLE
Liquid Exception: undefined method `transform_values'

### ISSUE THREAD

**Issue by jazibsawar** [robwierzbowski/jekyll-picture-tag#91]
I installed the plugin and configured it as per documentation. But when I tried to use the plugin it gave me this error `Liquid Exception: undefined method 'transform_values' for {nil=>"17.png"}:Hash in about.md`.

My _config.yml:
```
# Picture
picture: 
  source: "assets/images/_fullsize"
  output: "generated" 
  suppress_warnings: false
```

My pitcure.yml:
```
media_presets:
  wide_desktop: 'min-width: 1801px'
  desktop: 'max-width: 1800px'
  wide_tablet: 'max-width: 1200px'
  tablet: 'max-width: 900px'
  mobile: 'max-width: 600px'
markup_presets:
  default:
    markup: auto
    formats: [webp, original]
    widths: [200, 400, 800, 1600]
    media_widths: 
      mobile: [200, 400, 600] 
      tablet: [400, 600, 800]
    size: 800px
    sizes: 
      mobile: 100vw
      desktop: 60vw
    fallback_width: 800
    fallback_format: original
    attributes:
      picture: 'class="awesome" data-volume="11"'
      img: 'class="some-other-class"'
```
